app = 'gifspin'
primary_region = 'yyz'

swap_size_mb = 2048

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  LISTEN = ':3000'
  OPT_DISPATCH_SIZE = '1'
  OPT_SHUTDOWN_MS = '20000'
  OPT_TIMEOUT_MS = '15000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = '3s'
  interval = '30s'
  timeout = '5s'
  method = 'GET'
  path = '/'
