app = 'gifspin'
primary_region = 'sea'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]

[env]
  LISTEN = ':3000'
  PATH_TEMP = '/tmp'
  OPT_DISPATCH_SIZE = '1'
  OPT_SHUTDOWN_MS = '20000'
  OPT_TIMEOUT_MS = '15000'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
